insert into t_category(category_nm, category_order, category_use_yn) values("헬스 · 다이어트",10100,0);
insert into t_category(category_nm, category_order, category_use_yn) values("필라테스 · 요가",10200,0);
insert into t_category(category_nm, category_order, category_use_yn) values("크로스핏 · 역도",10300,0);
insert into t_category(category_nm, category_order, category_use_yn) values("맨몸운동 · 체조",10400,0);
insert into t_category(category_nm, category_order, category_use_yn) values("수영 · 수상레저",10500,0);
insert into t_category(category_nm, category_order, category_use_yn) values("스키 · 스노보드",10600,0);
insert into t_category(category_nm, category_order, category_use_yn) values("배드민턴 · 테니스 · 탁구",10700,0);
insert into t_category(category_nm, category_order, category_use_yn) values("태권도 · 복싱 · MMA",10800,0);
insert into t_category(category_nm, category_order, category_use_yn) values("주짓수 · 유도 · 레슬링",10900,0);
insert into t_category(category_nm, category_order, category_use_yn) values("등산 · 클라이밍",11000,0);
insert into t_category(category_nm, category_order, category_use_yn) values("축구 · 농구 · 야구",11100,0);
insert into t_category(category_nm, category_order, category_use_yn) values("골프 · 당구",11200,0);
insert into t_category(category_nm, category_order, category_use_yn) values("자전거 · 스케이트보드",11300,0);